### ISSUE TITLE
Boot2Qt on Yocto Zeus VAR-SOM-6UL ?

### ISSUE THREAD

**Issue by esutton** [varigit/meta-variscite-boot2qt#1]
Is there a B2QT Zeus branch available?

Any links you can post to point me how to build Yocto Zeus image for VAR-SOM-6UL ?

I am starting a new project and wanted to start with Zeus.  A Variscite engineer told me Zeus was out in mid October. 

Thanks in advance,

-Ed

**Comment by eranmati** [comment]
Hi Ed.
B2Qt Zeus for the VAR-SOM-6UL is expected to be released by early next week.

Regards,
Eran

**Comment by NMSTEC** [comment]
I was unable to locate the b2qt package for the VAR-SOM-6UL, is this something you can help me locate?

**Comment by eranmati** [comment]
@NMSTEC, see:
https://variwiki.com
https://variwiki.com/index.php?title=VAR-SOM-6UL
