### ISSUE TITLE
kirkstone-var01 for imx7-var-som Machine

### ISSUE THREAD

**Issue by AYJF** [varigit/meta-variscite-boot2qt#3]
Hello , I have a VAR-SOM-MX7 and I want to create a Linux distribution and the Qt toolchain, I know the meta-variscite-boot2qt for dunfell-var01 is provided ,  but I have Ubuntu 22.04 as host machine and I got some issues with dunfell branch, I was wondering if  meta-variscite-boot2qt  (kirkstone-var01 branch ) have or will have support for imx7-var-som machine.. Thanks in advance

**Comment by varigigi** [comment]
@AYJF, I would suggest using an Ubuntu 20.04 docker container as reported in build instructions of the [wiki](https://variwiki.com/index.php?title=VAR-SOM-MX7_B2QT&release=mx7-b2qt-dunfell-5.4-2.1.x-v1.1).
Please let me know if you need further details.
Thanks

**Comment by AYJF** [comment]
@varigigi got it Thanks , Just a couple of questions. How can I use a more update version of linux kernel , with my imx7-var-som? and How can the freeRTOS layer is supported for imx7-var-som machine?

**Comment by varigigi** [comment]
@AYJF, please refer to our wiki pages for [VAR-SOM-MX7](https://variwiki.com/index.php?title=VAR-SOM-MX7).
If you need further assistance, kindly register as customer to our [portal](https://varisciteportal.axosoft.com/).
Thanks
